services:
  - type: web
    name: tfe-flask-vite
    env: python
    rootDir: .

    plan: free

    buildCommand: ./build.sh
    startCommand: cd backend && gunicorn app:app -b 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

    build:
      python:
        requirementsPath: backend/requirements.txt
