services:
  - type: web
    name: tfe-flask-vite
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    rootDir: backend
    plan: free
